// lib/menu-data.ts
import { MenuItem } from "@/types";

export const menuItems: MenuItem[] = [
  // ==================== BEEF BURGERS ====================
  {
    slug: "cheesy-buffalo",
    name: "Cheesy Buffalo",
    category: "beef",
    price: 10.5,
    description:
      "Brioche bun, homemade 140g beef patty, cheese, burger sauce, cucumber, onion, tomatoes, lettuce",
    spiceLevel: 3,
    image: "/burgers/beef/Cheesy-Buffalo_10,50euros.webp",
    gallery: [
      "/burgers/beef/Cheesy-Buffalo_10,50euros.webp",
      "/burgers/beef/Cheese-Burger_7euros.webp",
    ],
    ingredients: [
      { name: "Beef Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Onion" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 650,
      protein: 32,
      fat: 38,
      carbs: 48,
      allergens: ["Gluten", "Dairy"],
    },
    preparationTime: 12,
    rating: 4.8,
    bestseller: true,
    chefRecommendation: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Patty", price: 3.0 },
        { name: "Extra Sauce", price: 0.5 },
        { name: "Jalapenos", price: 1.0 },
      ],
      removals: ["Onion", "Tomatoes", "Cucumber", "Lettuce"],
    },
    relatedSlugs: ["angry-bull", "smokie-beefy-bbq", "cheese-burger"],
  },
  {
    slug: "angry-bull",
    name: "Angry Bull",
    category: "beef",
    price: 12.0,
    description:
      "Brioche bun, homemade 140g beef patty, cheese, chili cheese sauce, jalapeno, cucumber, onion, lettuce",
    spiceLevel: 3,
    image: "/burgers/beef/Angry-Bull_12euros.webp",
    gallery: [
      "/burgers/beef/Angry-Bull_12euros.webp",
    ],
    ingredients: [
      { name: "Beef Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Chili Cheese Sauce" },
      { name: "Jalapenos" },
      { name: "Cucumber" },
      { name: "Onion" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 720,
      protein: 34,
      fat: 42,
      carbs: 50,
      allergens: ["Gluten", "Dairy", "Mustard"],
    },
    preparationTime: 12,
    rating: 4.9,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Patty", price: 3.0 },
        { name: "Extra Jalapenos", price: 1.0 },
        { name: "Bacon", price: 2.0 },
      ],
      removals: ["Jalapeno", "Cucumber", "Onion", "Lettuce"],
    },
    relatedSlugs: ["cheesy-buffalo", "blazing-nacho-beef", "smokie-beefy-bbq"],
  },
  {
    slug: "smokie-beefy-bbq",
    name: "Smokie Beefy BBQ",
    category: "beef",
    price: 13.0,
    description:
      "Brioche bun, homemade 140g beef patty, cheese, burger sauce, cucumber, onion rings, crispy onions, BBQ sauce, tomatoes, lettuce",
    spiceLevel: 3,
    image: "/burgers/beef/Smookie-Beefy-BBQ_13euros.webp",
    gallery: [
      "/burgers/beef/Smookie-Beefy-BBQ_13euros.webp",
    ],
    ingredients: [
      { name: "Beef Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Onion Rings" },
      { name: "Crispy Onions" },
      { name: "BBQ Sauce" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 820,
      protein: 36,
      fat: 46,
      carbs: 64,
      allergens: ["Gluten", "Dairy", "Sulphites"],
    },
    preparationTime: 14,
    rating: 4.7,
    chefRecommendation: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Patty", price: 3.0 },
        { name: "Extra Bacon", price: 2.0 },
      ],
      removals: ["Cucumber", "Onion Rings", "Crispy Onions", "Tomatoes", "Lettuce"],
    },
    relatedSlugs: ["cheesy-buffalo", "angry-bull", "blazing-nacho-beef"],
  },
  {
    slug: "blazing-nacho-beef",
    name: "Blazing Nacho Beef",
    category: "beef",
    price: 13.0,
    description:
      "Brioche bun, homemade 140g beef patty, cheese, burger sauce, cucumber, jalapeno, nachos, sriracha sauce, tomatoes, lettuce",
    spiceLevel: 3,
    image: "/burgers/beef/Blazing-Nacho-Beef_13euros.webp",
    gallery: [
      "/burgers/beef/Blazing-Nacho-Beef_13euros.webp",
    ],
    ingredients: [
      { name: "Beef Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Jalapenos" },
      { name: "Crunchy Nachos" },
      { name: "Sriracha Sauce" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 780,
      protein: 33,
      fat: 40,
      carbs: 58,
      allergens: ["Gluten", "Dairy"],
    },
    preparationTime: 13,
    rating: 4.6,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Patty", price: 3.0 },
        { name: "Extra Nachos", price: 1.2 },
      ],
      removals: ["Cucumber", "Jalapeno", "Nachos", "Tomatoes", "Lettuce"],
    },
    relatedSlugs: ["angry-bull", "smokie-beefy-bbq", "cheesy-buffalo"],
  },
  {
    slug: "cheese-burger",
    name: "Cheese Burger",
    category: "beef",
    price: 7.0,
    description:
      "Brioche bun, homemade 140g beef patty, cheese, burger sauce, cucumber, onion, tomatoes, lettuce",
    spiceLevel: 1,
    image: "/burgers/beef/Cheese-Burger_7euros.webp",
    gallery: [
      "/burgers/beef/Cheese-Burger_7euros.webp",
    ],
    ingredients: [
      { name: "Beef Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Onion" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 610,
      protein: 30,
      fat: 34,
      carbs: 46,
      allergens: ["Gluten", "Dairy"],
    },
    preparationTime: 10,
    rating: 4.8,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Patty", price: 3.0 },
      ],
      removals: ["Onion", "Tomatoes", "Cucumber", "Lettuce"],
    },
    relatedSlugs: ["cheesy-buffalo", "angry-bull", "loaded-crunchy"],
  },

  // ==================== CHICKEN BURGERS ====================
  {
    slug: "crunchy-chicken",
    name: "Crunchy Chicken",
    category: "chicken",
    price: 8.5,
    description: "Brioche bun, chicken strips, cheese, burger sauce, lettuce",
    spiceLevel: 2,
    image: "/burgers/chicken/Chrunchy-Chicken_8,50euros.webp",
    gallery: ["/burgers/chicken/Chrunchy-Chicken_8,50euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 590,
      protein: 26,
      fat: 29,
      carbs: 52,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 10,
    rating: 4.7,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Chicken Strip", price: 2.5 },
        { name: "Extra Sauce", price: 0.5 },
      ],
      removals: ["Lettuce"],
    },
    relatedSlugs: ["loaded-crunchy", "crispy-ringer", "flip-chicken-burger"],
  },
  {
    slug: "loaded-crunchy",
    name: "Loaded Crunchy",
    category: "chicken",
    price: 9.0,
    description:
      "Brioche bun, chicken strips, cheese, burger sauce, tomatoes, onion, cucumber, lettuce",
    spiceLevel: 2,
    image: "/burgers/chicken/Loaded-Chrunchy_9euros.webp",
    gallery: ["/burgers/chicken/Loaded-Chrunchy_9euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Tomatoes" },
      { name: "Onion" },
      { name: "Cucumber" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 630,
      protein: 28,
      fat: 32,
      carbs: 55,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 11,
    rating: 4.8,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Chicken Strip", price: 2.5 },
      ],
      removals: ["Tomatoes", "Onion", "Cucumber", "Lettuce"],
    },
    relatedSlugs: ["crunchy-chicken", "crispy-ringer", "foodie-bomber"],
  },
  {
    slug: "crispy-ringer",
    name: "Crispy Ringer",
    category: "chicken",
    price: 10.0,
    description:
      "Brioche bun, chicken strips, cheese, burger sauce, onion rings, onion, tomatoes, lettuce",
    spiceLevel: 2,
    image: "/burgers/chicken/Crispy-Ringer_10euros.webp",
    gallery: ["/burgers/chicken/Crispy-Ringer_10euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Onion Rings" },
      { name: "Onion" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 710,
      protein: 30,
      fat: 36,
      carbs: 63,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 12,
    rating: 4.6,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Chicken Strip", price: 2.5 },
        { name: "Bacon", price: 2.0 },
      ],
      removals: ["Onion Rings", "Onion", "Tomatoes", "Lettuce"],
    },
    relatedSlugs: ["loaded-crunchy", "mexican-cracker", "foodie-bomber"],
  },
  {
    slug: "mexican-cracker",
    name: "Mexican Cracker",
    category: "chicken",
    price: 11.0,
    description:
      "Brioche bun, chicken strips, cheese, burger sauce, jalapeno, cucumber, nachos, sriracha sauce, onion, lettuce",
    spiceLevel: 2,
    image: "/burgers/chicken/Mexican-Cracker_11euros.webp",
    gallery: ["/burgers/chicken/Mexican-Cracker_11euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Jalapenos" },
      { name: "Cucumber" },
      { name: "Nachos" },
      { name: "Sriracha Sauce" },
      { name: "Onion" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 740,
      protein: 29,
      fat: 35,
      carbs: 68,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 12,
    rating: 4.7,
    chefRecommendation: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Chicken Strip", price: 2.5 },
        { name: "Extra Nachos", price: 1.2 },
      ],
      removals: ["Jalapeno", "Cucumber", "Nachos", "Onion", "Lettuce"],
    },
    relatedSlugs: ["crispy-ringer", "foodie-bomber", "blazing-nacho-beef"],
  },
  {
    slug: "flip-chicken-burger",
    name: "Flip Chicken Burger",
    category: "chicken",
    price: 6.0,
    description: "Brioche bun, chicken strips, cheese, burger sauce, lettuce",
    spiceLevel: 1,
    image: "/burgers/chicken/Flip-Chicken-Burger_6euros.webp",
    gallery: ["/burgers/chicken/Flip-Chicken-Burger_6euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 520,
      protein: 24,
      fat: 24,
      carbs: 48,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 8,
    rating: 4.5,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
      ],
      removals: ["Lettuce"],
    },
    relatedSlugs: ["crunchy-chicken", "cheese-burger", "loaded-crunchy"],
  },
  {
    slug: "foodie-bomber",
    name: "Foodie Bomber",
    category: "chicken",
    price: 13.0,
    description:
      "Brioche bun, chicken strips, cheese, chili cheese nuggets, chili cheese sauce, onion, jalapeno, lettuce",
    spiceLevel: 2,
    image: "/burgers/chicken/Foodie-Bomber-13euros.webp",
    gallery: ["/burgers/chicken/Foodie-Bomber-13euros.webp"],
    ingredients: [
      { name: "Chicken Strips" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Chili Cheese Nuggets" },
      { name: "Chili Cheese Sauce" },
      { name: "Onion" },
      { name: "Jalapenos" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 880,
      protein: 34,
      fat: 48,
      carbs: 72,
      allergens: ["Gluten", "Dairy", "Egg"],
    },
    preparationTime: 14,
    rating: 4.9,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Chicken Strip", price: 2.5 },
        { name: "Extra Nuggets", price: 2.0 },
      ],
      removals: ["Chili Cheese Nuggets", "Onion", "Jalapeno", "Lettuce"],
    },
    relatedSlugs: ["loaded-crunchy", "crispy-ringer", "mexican-cracker"],
  },

  // ==================== VEGGIE BURGERS ====================
  {
    slug: "plant-power",
    name: "Plant Power",
    category: "veggie",
    price: 9.0,
    description:
      "Brioche bun, falafel patty, cheese, burger sauce, cucumber, lettuce, onion, tomatoes",
    spiceLevel: 0,
    image: "/graphics/tasty burger.svg",
    gallery: ["/graphics/tasty burger.svg"],
    ingredients: [
      { name: "Falafel Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Lettuce" },
      { name: "Onion" },
      { name: "Tomatoes" },
    ],
    nutrition: {
      calories: 560,
      protein: 18,
      fat: 22,
      carbs: 62,
      allergens: ["Gluten", "Dairy", "Sesame"],
    },
    preparationTime: 10,
    rating: 4.6,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Falafel", price: 2.5 },
      ],
      removals: ["Cucumber", "Lettuce", "Onion", "Tomatoes"],
    },
    relatedSlugs: ["veggie-bbq", "cheese-burger"],
  },
  {
    slug: "veggie-bbq",
    name: "Veggie BBQ",
    category: "veggie",
    price: 11.0,
    description:
      "Brioche bun, falafel patty, cheese, burger sauce, cucumber, onion rings, crispy onions, BBQ sauce, tomatoes, lettuce",
    spiceLevel: 0,
    image: "/graphics/tasty burger.svg",
    gallery: ["/graphics/tasty burger.svg"],
    ingredients: [
      { name: "Falafel Patty" },
      { name: "Brioche Bun" },
      { name: "Cheddar Cheese" },
      { name: "Burger Sauce" },
      { name: "Cucumber" },
      { name: "Onion Rings" },
      { name: "Crispy Onions" },
      { name: "BBQ Sauce" },
      { name: "Tomatoes" },
      { name: "Lettuce" },
    ],
    nutrition: {
      calories: 680,
      protein: 20,
      fat: 28,
      carbs: 76,
      allergens: ["Gluten", "Dairy", "Sesame", "Sulphites"],
    },
    preparationTime: 12,
    rating: 4.5,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Extra Cheese", price: 1.5 },
        { name: "Extra Falafel", price: 2.5 },
      ],
      removals: ["Cucumber", "Onion Rings", "Crispy Onions", "Tomatoes", "Lettuce"],
    },
    relatedSlugs: ["plant-power", "smokie-beefy-bbq"],
  },

  // ==================== DRINKS ====================
  {
    slug: "coca-cola",
    name: "Coca Cola",
    category: "drink",
    price: 2.5,
    description: "330ml Dose - Classic refreshing Coca-Cola soft drink",
    spiceLevel: 0,
    image: "/graphics/cold drinks sprite cola fanta.svg",
    gallery: ["/graphics/cold drinks sprite cola fanta.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Sugar" }, { name: "Caramel Color" }, { name: "Caffeine" }],
    nutrition: { calories: 139, protein: 0, fat: 0, carbs: 35 },
    preparationTime: 2,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["coca-cola-zero", "fanta", "sprite", "wasser"],
  },
  {
    slug: "coca-cola-zero",
    name: "Coca Cola Zero",
    category: "drink",
    price: 2.5,
    description: "330ml Dose - Sugar-free Coca-Cola taste",
    spiceLevel: 0,
    image: "/graphics/cold drinks sprite cola fanta.svg",
    gallery: ["/graphics/cold drinks sprite cola fanta.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Aspartame" }, { name: "Caramel Color" }, { name: "Caffeine" }],
    nutrition: { calories: 0, protein: 0, fat: 0, carbs: 0 },
    preparationTime: 2,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["coca-cola", "fanta", "sprite", "wasser"],
  },
  {
    slug: "fanta",
    name: "Fanta",
    category: "drink",
    price: 2.5,
    description: "330ml Dose - Refreshing orange flavor soft drink",
    spiceLevel: 0,
    image: "/graphics/cold drinks sprite cola fanta.svg",
    gallery: ["/graphics/cold drinks sprite cola fanta.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Sugar" }, { name: "Orange Juice from Concentrate" }, { name: "Citric Acid" }],
    nutrition: { calories: 130, protein: 0, fat: 0, carbs: 32 },
    preparationTime: 2,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["coca-cola", "sprite", "mezzo-mix", "wasser"],
  },
  {
    slug: "sprite",
    name: "Sprite",
    category: "drink",
    price: 2.5,
    description: "330ml Dose - Crisp lemon-lime sparkling beverage",
    spiceLevel: 0,
    image: "/graphics/cold drinks sprite cola fanta.svg",
    gallery: ["/graphics/cold drinks sprite cola fanta.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Sugar" }, { name: "Citric Acid" }, { name: "Natural Flavors" }],
    nutrition: { calories: 120, protein: 0, fat: 0, carbs: 30 },
    preparationTime: 2,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["coca-cola", "fanta", "mezzo-mix", "wasser"],
  },
  {
    slug: "capri-sonne",
    name: "Capri Sonne",
    category: "drink",
    price: 1.5,
    description: "200ml - Multi-fruit juice pouch for children and adults",
    spiceLevel: 0,
    image: "/graphics/caprisun.svg",
    gallery: ["/graphics/caprisun.svg"],
    ingredients: [{ name: "Water" }, { name: "Sugar" }, { name: "Lemon Juice" }, { name: "Orange Juice" }, { name: "Spring Water" }],
    nutrition: { calories: 78, protein: 0.1, fat: 0, carbs: 19 },
    preparationTime: 2,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["wasser", "coca-cola", "fanta"],
  },
  {
    slug: "wasser",
    name: "Wasser",
    category: "drink",
    price: 2.0,
    description: "500ml - Pure still mineral spring water",
    spiceLevel: 0,
    image: "/graphics/water.svg",
    gallery: ["/graphics/water.svg"],
    ingredients: [{ name: "Mineral Spring Water" }],
    nutrition: { calories: 0, protein: 0, fat: 0, carbs: 0 },
    preparationTime: 1,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["coca-cola", "coca-cola-zero", "fanta", "sprite"],
  },
  {
    slug: "mezzo-mix",
    name: "Mezzo Mix",
    category: "drink",
    price: 2.5,
    description: "330ml Dose - Delicious combination of cola and orange flavor",
    spiceLevel: 0,
    image: "/graphics/cold drinks sprite cola fanta.svg",
    gallery: ["/graphics/cold drinks sprite cola fanta.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Sugar" }, { name: "Orange Juice" }, { name: "Cola Flavoring" }],
    nutrition: { calories: 135, protein: 0, fat: 0, carbs: 33 },
    preparationTime: 2,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["coca-cola", "fanta", "sprite", "wasser"],
  },
  {
    slug: "red-bull",
    name: "Red Bull",
    category: "drink",
    price: 3.5,
    description: "250ml Dose - Energy drink that vitalizes body and mind",
    spiceLevel: 0,
    image: "/graphics/redbull.svg",
    gallery: ["/graphics/redbull.svg"],
    ingredients: [{ name: "Carbonated Water" }, { name: "Sucrose" }, { name: "Taurine" }, { name: "Caffeine" }, { name: "B-Group Vitamins" }],
    nutrition: { calories: 115, protein: 0.3, fat: 0, carbs: 27 },
    preparationTime: 2,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["coca-cola-zero", "wasser"],
  },

  // ==================== APPETIZERS / SIDES ====================
  {
    slug: "chili-cheese-nuggets",
    name: "Chili Cheese Nuggets",
    category: "appetizer",
    price: 5.0,
    description: "Crispy fried nuggets filled with smooth melted cheese and spicy jalapeño pieces. (6 Pieces base)",
    spiceLevel: 2,
    image: "/Appetizers/Chilli-Cheese-Nuggets.webp",
    gallery: ["/Appetizers/Chilli-Cheese-Nuggets.webp"],
    ingredients: [{ name: "Melted Processed Cheese" }, { name: "Jalapeño Pieces" }, { name: "Crispy Breaded Coating" }],
    nutrition: { calories: 340, protein: 9, fat: 22, carbs: 26, allergens: ["Gluten", "Dairy"] },
    preparationTime: 6,
    rating: 4.8,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Upgrade to 10 Pieces", price: 2.5 },
        { name: "Upgrade to 16 Pieces", price: 6.0 },
      ],
      removals: [],
    },
    relatedSlugs: ["mozzarella-sticks", "onion-rings", "fries"],
  },
  {
    slug: "mozzarella-sticks",
    name: "Mozzarella Sticks",
    category: "appetizer",
    price: 5.0,
    description: "Golden fried breaded mozzarella cheese sticks, crispy outside, gooey inside. (4 Pieces base)",
    spiceLevel: 0,
    image: "/Appetizers/Mozarella-Sticks.webp",
    gallery: ["/Appetizers/Mozarella-Sticks.webp"],
    ingredients: [{ name: "Mozzarella Cheese" }, { name: "Italian Breadcrumb Seasoning" }],
    nutrition: { calories: 290, protein: 12, fat: 18, carbs: 21, allergens: ["Gluten", "Dairy"] },
    preparationTime: 6,
    rating: 4.7,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Upgrade to 8 Pieces", price: 4.0 },
        { name: "Upgrade to 14 Pieces", price: 9.0 },
      ],
      removals: [],
    },
    relatedSlugs: ["chili-cheese-nuggets", "onion-rings", "fries"],
  },
  {
    slug: "onion-rings",
    name: "Onion Rings",
    category: "appetizer",
    price: 4.0,
    description: "Crispy beer-battered sliced onion rings fried to a perfect golden brown. (6 Pieces base)",
    spiceLevel: 0,
    image: "/Appetizers/Onion-Rings.webp",
    gallery: ["/Appetizers/Onion-Rings.webp"],
    ingredients: [{ name: "Fresh White Onions" }, { name: "Crispy Beer Batter" }],
    nutrition: { calories: 260, protein: 4, fat: 12, carbs: 34, allergens: ["Gluten"] },
    preparationTime: 5,
    rating: 4.6,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Upgrade to 12 Pieces", price: 3.0 },
        { name: "Upgrade to 24 Pieces", price: 8.0 },
      ],
      removals: [],
    },
    relatedSlugs: ["chili-cheese-nuggets", "mozzarella-sticks", "fries"],
  },
  {
    slug: "fries",
    name: "Fries",
    category: "appetizer",
    price: 3.5,
    description: "Golden, crispy French fries lightly seasoned with salt.",
    spiceLevel: 0,
    image: "/Appetizers/Pommes_3,5euros.webp",
    gallery: ["/Appetizers/Pommes_3,5euros.webp"],
    ingredients: [{ name: "Premium Potatoes" }, { name: "Sea Salt" }],
    nutrition: { calories: 310, protein: 3.5, fat: 14, carbs: 41, allergens: [] },
    preparationTime: 5,
    rating: 4.9,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Add Cheddar Cheese Sauce", price: 1.5 },
        { name: "Add Chili Cheese Sauce", price: 1.8 },
      ],
      removals: [],
    },
    relatedSlugs: ["chili-cheese-nuggets", "mozzarella-sticks", "onion-rings"],
  },

  // ==================== FRIED CHICKEN ====================
  {
    slug: "chicken-wings",
    name: "Chicken Wings",
    category: "fried-chicken",
    price: 7.5,
    description: "Crispy fried halal chicken wings tossed in secret spices. (6 Pieces base)",
    spiceLevel: 2,
    image: "/Fried-Chicken/Chicken-Wings.webp",
    gallery: ["/Fried-Chicken/Chicken-Wings.webp"],
    ingredients: [{ name: "Halal Chicken Wings" }, { name: "Crispy Spiced Batter Coating" }],
    nutrition: { calories: 480, protein: 34, fat: 32, carbs: 12, allergens: ["Gluten"] },
    preparationTime: 10,
    rating: 4.8,
    bestseller: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Upgrade to 10 Pieces", price: 3.5 },
        { name: "Upgrade to 20 Pieces", price: 12.50 },
      ],
      removals: [],
    },
    relatedSlugs: ["chicken-strips", "chili-cheese-nuggets"],
  },
  {
    slug: "chicken-strips",
    name: "Chicken Strips",
    category: "fried-chicken",
    price: 6.0,
    description: "Tender, juicy breaded halal chicken breast strips fried until crispy. (3 Pieces base)",
    spiceLevel: 2,
    image: "/Fried-Chicken/Chicken-Stripes.webp",
    gallery: ["/Fried-Chicken/Chicken-Stripes.webp"],
    ingredients: [{ name: "Halal Chicken Breast Fillets" }, { name: "Southern Style Seasoned Breading" }],
    nutrition: { calories: 420, protein: 28, fat: 22, carbs: 18, allergens: ["Gluten", "Egg"] },
    preparationTime: 9,
    rating: 4.9,
    chefRecommendation: true,
    halal: true,
    customizationOptions: {
      extras: [
        { name: "Upgrade to 6 Pieces", price: 5.5 },
        { name: "Upgrade to 9 Pieces", price: 10.0 },
      ],
      removals: [],
    },
    relatedSlugs: ["chicken-wings", "chili-cheese-nuggets"],
  },

  // ==================== DIPS ====================
  {
    slug: "mayo",
    name: "Mayo",
    category: "dip",
    price: 0.5,
    description: "Creamy classic mayonnaise",
    spiceLevel: 0,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Vegetable Oil" }, { name: "Egg Yolk" }, { name: "Vinegar" }],
    nutrition: { calories: 90, protein: 0.1, fat: 10, carbs: 0.5, allergens: ["Egg", "Mustard"] },
    preparationTime: 1,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["ketchup", "foodie-burger-sauce"],
  },
  {
    slug: "ketchup",
    name: "Ketchup",
    category: "dip",
    price: 0.5,
    description: "Sweet tomato ketchup made from ripe tomatoes",
    spiceLevel: 0,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Tomato Concentrate" }, { name: "Sugar" }, { name: "Vinegar" }, { name: "Spices" }],
    nutrition: { calories: 15, protein: 0.2, fat: 0.1, carbs: 3.7 },
    preparationTime: 1,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["mayo", "foodie-burger-sauce"],
  },
  {
    slug: "garlic-flip",
    name: "Garlic Flip",
    category: "dip",
    price: 1.0,
    description: "Creamy mayonnaise blended with intense aromatic garlic and herbs",
    spiceLevel: 1,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Creamy Mayo Base" }, { name: "Garlic Purée" }, { name: "Chives" }],
    nutrition: { calories: 95, protein: 0.2, fat: 10, carbs: 1.2, allergens: ["Egg"] },
    preparationTime: 1,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["mayo", "foodie-burger-sauce", "sweet-chili-magic"],
  },
  {
    slug: "blazing-bbq",
    name: "Blazing BBQ",
    category: "dip",
    price: 1.0,
    description: "Smoky and sweet BBQ sauce with a kick of spices",
    spiceLevel: 1,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Tomato Paste" }, { name: "Molasses" }, { name: "Liquid Smoke" }, { name: "Spices" }],
    nutrition: { calories: 45, protein: 0.3, fat: 0.1, carbs: 11, allergens: ["Sulphites"] },
    preparationTime: 1,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["smokie-volcano", "ketchup"],
  },
  {
    slug: "super-curry",
    name: "Super Curry",
    category: "dip",
    price: 1.0,
    description: "Flavorful curry sauce with authentic German street food style spices",
    spiceLevel: 2,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Tomato Paste" }, { name: "Curry Powder Blend" }, { name: "Apple Juice Concentrate" }],
    nutrition: { calories: 40, protein: 0.4, fat: 0.2, carbs: 9.5 },
    preparationTime: 1,
    rating: 4.7,
    halal: true,
    relatedSlugs: ["ketchup", "dragons-flame"],
  },
  {
    slug: "dragon-s-flame",
    name: "Dragon's Flame",
    category: "dip",
    price: 1.0,
    description: "Fiery hot sauce for spice lovers, made with red chili peppers and vinegar",
    spiceLevel: 3,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Red Chili Mash" }, { name: "Distilled Vinegar" }, { name: "Garlic Powder" }],
    nutrition: { calories: 10, protein: 0.1, fat: 0, carbs: 2.1 },
    preparationTime: 1,
    rating: 4.9,
    halal: true,
    relatedSlugs: ["smokie-volcano", "tangy-chili-cheese"],
  },
  {
    slug: "smokie-volcano",
    name: "Smokie Volcano",
    category: "dip",
    price: 1.0,
    description: "A combination of creamy chipotle mayo and intense hickory BBQ smoke",
    spiceLevel: 2,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Chipotle Pepper Paste" }, { name: "Mayo Base" }, { name: "Smoky BBQ Sauce" }],
    nutrition: { calories: 85, protein: 0.2, fat: 8.5, carbs: 2.4, allergens: ["Egg"] },
    preparationTime: 1,
    rating: 4.8,
    halal: true,
    relatedSlugs: ["blazing-bbq", "dragon-s-flame"],
  },
  {
    slug: "sweet-chili-magic",
    name: "Sweet Chili Magic",
    category: "dip",
    price: 1.0,
    description: "Sweet and tangy Thai-style sweet chili dipping sauce",
    spiceLevel: 1,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Sugar" }, { name: "Water" }, { name: "Pickled Red Chili" }, { name: "Garlic" }],
    nutrition: { calories: 50, protein: 0.1, fat: 0, carbs: 12.5 },
    preparationTime: 1,
    rating: 4.7,
    halal: true,
    relatedSlugs: ["ketchup", "garlic-flip"],
  },
  {
    slug: "tangy-chili-cheese",
    name: "Tangy Chili Cheese",
    category: "dip",
    price: 1.0,
    description: "Creamy cheese sauce with spicy jalapeño flavor, perfect for dipping",
    spiceLevel: 2,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Water" }, { name: "Cheddar Cheese Blend" }, { name: "Whey" }, { name: "Jalapeño Purée" }],
    nutrition: { calories: 75, protein: 1.5, fat: 6, carbs: 4, allergens: ["Dairy"] },
    preparationTime: 1,
    rating: 4.9,
    bestseller: true,
    halal: true,
    relatedSlugs: ["dragon-s-flame", "foodie-burger-sauce"],
  },
  {
    slug: "foodie-burger-sauce",
    name: "Foodie Burger Sauce",
    category: "dip",
    price: 1.0,
    description: "Our signature wagon sauce, secret recipe with mustard, herbs, and pickle relish",
    spiceLevel: 1,
    image: "/graphics/dips.svg",
    gallery: ["/graphics/dips.svg"],
    ingredients: [{ name: "Secret Wagon Mayo Base" }, { name: "Sweet Pickle Relish" }, { name: "Yellow Mustard" }, { name: "Spices" }],
    nutrition: { calories: 88, protein: 0.2, fat: 8.8, carbs: 1.8, allergens: ["Egg", "Mustard"] },
    preparationTime: 1,
    rating: 4.9,
    chefRecommendation: true,
    halal: true,
    relatedSlugs: ["mayo", "tangy-chili-cheese", "garlic-flip"],
  },
];

// Helper to get all slugs
export function getAllSlugs() {
  return menuItems.map((item) => item.slug);
}

// Helper to get item by slug
export function getItemBySlug(slug: string): MenuItem | undefined {
  return menuItems.find((item) => item.slug === slug);
}

// Helper for related items
export function getRelatedItems(slugs: string[]): MenuItem[] {
  return menuItems.filter((item) => slugs.includes(item.slug));
}
